### PR TITLE
Add tab bar UI and functionality to switch between different pages

### PR DESCRIPTION
**Pull request by jennifermtan**
https://github.com/keen-app/keen/assets/63948459/9df266ec-acda-4238-85e3-5e691e72d795

### CODE REVIEW

**Comment by jennifermtan** [comment]
Hi @jesstn,
I added the icons for the tab bar but there is an issue because it's not easy to resize image in TabView. Wanted to check if this size is fine before trying to customise the size because it will take some time. Thanks!

Another option is I can add text like this:
Simulator Screenshot - iPhone 15 - 2024-04-29 at 15 17 02

**Comment by jesstn** [comment]
Hi @jennifermtan looks great! I actually like the version with the text better

**Comment by jennifermtan** [comment]
> Hi @jennifermtan looks great! I actually like the version with the text better

Great! The latest commit has the text :)
Simulator Screenshot - iPhone 15 - 2024-04-29 at 16 25 38

**Comment by gitparth12** [comment]
Great work Jenny! I believe the version with the text looks a bit better.

**Review by antrikshdhand — APPROVED** [review]
It's all coming together!! Also I agree, the text under the icons looks great. Nice work :D

**Review by gitparth12 — APPROVED** [review]

**Pull request merged**
