### PR TITLE
Update database schema

### LINKED ISSUE #4: Create database schema
Currently, the schema in the Postgres server is just a sample schema I came up with on the fly. We need to sit down and think about our schema design (and in the process brush up on our ER diagram skills).

### PR DESCRIPTION
**Pull request by antrikshdhand**
Closes #4.

1. Converted the ER Diagram into a database schema (see `docs/database`)
2. Created `INSERT INTO` statements for the new database schema
3. Converted the database schema into `joi` commands for the Node.JS backend validation

Future steps:
- Expand the API to allow for query of relevant information
- Link the API with the frontend

### CODE REVIEW

**Comment by antrikshdhand** [comment]
I've taken a look at the DB diagram Parth made and combined it with the DB diagram I created in the initial commit.

Main changes:
- `Event` and `Collection` now have a many-to-many relationship. That is, an `Event` can be stored in many different user collections, and collections can contain many events.
- No need for the `Stores` table as a collection belongs to exactly one user, so we can just add a foreign key into `Collection` which references `User.email`.
- Changed the datatype for `id` columns to `SERIAL`, the auto-incrementing datatype in PostgreSQL.
- Added an `id` column to `Collection`, so we can refer to a collection by its `id` rather than its `name`. Also, this allows for various users to create collections with the same name.
- Changed the datatype for `Event.visibility` to an `ENUM` called `PRIVACY_SETTING` with only two options so far, `public` and `private`.
- Though I have got PostGIS working on the database, I think for now we should keep location as a `VARCHAR` rather than a `geometry`, simply because the UI input right now is still a text box. When (or if) we link the Google Maps API to the app, we can change this to a geographical data type.
- Added `ON CASCADE DELETE` statements where necessary.
- Changed `DATETIME` to `TIMESTAMPTZ` to account for timezones (also I don't think `DATETIME` is even a PostgreSQL datatype...Mandela effect for real).

Screenshot 2024-04-29 at 14 57 28

I'll push these changes in my next commit.

Two issues I'll create after this:
1. Update location input to be an address using the Google Maps API [tag: future ideas]
2. Add a checkbox to the "availability" page saying something along the lines of "This activity has no set date/time". When the user selects it, the boxes are greyed out. This allows for `Event.start` and `Event.end` to be optional entries.

**Comment by antrikshdhand** [comment]
Refer to #14 and #13 for the new issues discovered as a result of this PR.

**Comment by jennifermtan** [comment]
Looks good! I love the verb "keened" haha. Also thinking if we need a "preferred name" for users (this will be what's displayed on their profile).

**Review by jennifermtan — COMMENTED** [review]
Looks good (from the diagram)! I love the verb "keened" haha. Also thinking if we need a "preferred name" for users (this will be what's displayed on their profile). 

I added Parth as reviewer because I'm not too familiar with databases and Jess for the UI comment you mentioned.

**Review by gitparth12 — APPROVED** [review]

**Pull request merged**
